import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-input',
  template: `
    <p>
      input works!
    </p>
    <input [value]="title" 
    (keyup.enter)="changeTitle(inputElement)" #inputElement>
    <button (click)="changeTitle(inputElement)">Save</button>
    <p>The title is: {{ title }}</p>
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {
  @Output() submit: EventEmitter<string> = new EventEmitter;
  title: string = ' ';
  changeTitle(newTitle): void {
    this.submit.emit(newTitle.value);
  }
  generateTitle(): string {
    return 'This title was generated by a method';
  }
  constructor() {
    console.log('in constructor');
    //this.changeTitle('I love Angular');
    console.log(this.title);
   }

  ngOnInit() {
    setTimeout(()=> {
      this.title = 'This is not the title you are looking for.';
    }, 3000);
  }

}
